// <auto-generated />
using System;
using MedShare.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedShare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106022750_AddMedicamentosInstituicao")]
    partial class AddMedicamentosInstituicao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MedShare.Models.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoReceita")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DoadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeDoacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ValidadeDoacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoadorId");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Doacoes");
                });

            modelBuilder.Entity("MedShare.Models.Doador", b =>
                {
                    b.Property<int>("DoadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoadorCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DoadorId");

                    b.ToTable("Doadores");
                });

            modelBuilder.Entity("MedShare.Models.Instituicao", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstituicaoCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoEndereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("MedShare.Models.InstituicaoMedicamento", b =>
                {
                    b.Property<int>("InstituicaoMedicamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeCaixas")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstituicaoMedicamentoId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("InstituicaoId", "MedicamentoId")
                        .IsUnique();

                    b.ToTable("InstituicaoMedicamentos");
                });

            modelBuilder.Entity("MedShare.Models.Medicamento", b =>
                {
                    b.Property<int>("MedicamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MedicamentoId");

                    b.ToTable("Medicamentos");

                    b.HasData(
                        new
                        {
                            MedicamentoId = 1,
                            Nome = "Dipirona"
                        },
                        new
                        {
                            MedicamentoId = 2,
                            Nome = "Paracetamol"
                        },
                        new
                        {
                            MedicamentoId = 3,
                            Nome = "Amoxicilina"
                        },
                        new
                        {
                            MedicamentoId = 4,
                            Nome = "Omeprazol"
                        });
                });

            modelBuilder.Entity("MedShare.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MedShare.Models.Doacao", b =>
                {
                    b.HasOne("MedShare.Models.Doador", "Doador")
                        .WithMany()
                        .HasForeignKey("DoadorId");

                    b.HasOne("MedShare.Models.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doador");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("MedShare.Models.InstituicaoMedicamento", b =>
                {
                    b.HasOne("MedShare.Models.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedShare.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Medicamento");
                });
#pragma warning restore 612, 618
        }
    }
}
