// <auto-generated />
using MedShare.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedShare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030001720_TableInitial")]
    partial class TableInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MedShare.Models.Doador", b =>
                {
                    b.Property<int>("DoadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoadorCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DoadorId");

                    b.ToTable("Doadores");
                });

            modelBuilder.Entity("MedShare.Models.Instituicao", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstituicaoCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoEndereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("MedShare.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
